site_name: EnvEast Python Course
theme: bootstrap

site_url: https://ueapy.github.io/enveast_python_course
repo_url: https://github.com/ueapy/enveast_python_course
site_author: Denis Sergeev
site_favicon: favicon.png
docs_dir: src
site_dir: _site

pages:
  - Home: index.md
  - Programme: programme.md
  - Installation: installation.md
  - Resources: resources.md
  - Motivation: motivation.md
